export const SET_CATALOGUE = 'SET_CATALOGUE';
export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const REMOVE_FROM_ORDER = 'REMOVE_FROM_ORDER';
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';
export const RISE_COUNT = 'RISE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';
export const SET_LOADING = 'IS_LOADING';
export const SET_DELIVERY_COST = 'SET_DELIVERY_COST';